export const personalInfo = {
    name: 'Sarvesh Santosh Mokal',
    shortName: 'Sarvesh Mokal',
    title: 'Full Stack Developer',
    subtitle: 'AIML Enthusiast',
    degree: 'B.Tech in Information Technology (2022–2026)',
    college: 'Pillai College of Engineering, Navi Mumbai',
    cgpa: '9.05',
    location: 'New Panvel, Maharashtra, India',
    email: 'sarveshmokal105@gmail.com',
    phone: '9370061529',
    linkedin: 'https://www.linkedin.com/in/sarvesh-mokal-1381022a3/',
    github: 'https://github.com/sarvesh207590',
    leetcode: 'https://leetcode.com/u/sarveshmokal/',
    bio: 'A passionate B.Tech Graduate with a strong interest in Java, Web Development, and full-stack technologies. Hardworking, highly motivated, and eager to learn and implement new technologies. I enjoy solving problems and building efficient, scalable applications while continuously improving my technical and communication skills.',
}

export const skills = {
    Frontend: [
        { name: 'React.js', level: 90 },
        { name: 'Next.js', level: 85 },
        { name: 'TypeScript', level: 80 },
        { name: 'JavaScript', level: 90 },
        { name: 'Tailwind CSS', level: 85 },
        { name: 'Bootstrap', level: 88 },
        { name: 'HTML5', level: 95 },
        { name: 'CSS3', level: 90 },
    ],
    Backend: [
        { name: 'Node.js', level: 82 },
        { name: 'Express.js', level: 80 },
        { name: 'Spring Boot', level: 70 },
        { name: 'Spring', level: 68 },
        { name: 'Hibernate', level: 65 },
        { name: 'REST APIs', level: 85 },
    ],
    Databases: [
        { name: 'MongoDB', level: 82 },
        { name: 'MySQL', level: 80 },
    ],
    Programming: [
        { name: 'Java', level: 88 },
        { name: 'Python', level: 78 },
        { name: 'JavaScript', level: 90 },
        { name: 'C#', level: 65 },
        { name: '.NET', level: 60 },
        { name: 'SQL', level: 80 },
    ],
    Tools: [
        { name: 'Git', level: 88 },
        { name: 'GitHub', level: 88 },
        { name: 'Docker', level: 70 },
        { name: 'Postman', level: 85 },
        { name: 'VS Code', level: 95 },
        { name: 'Android Studio', level: 72 },
        { name: 'Jira', level: 70 },
        { name: 'AWS', level: 60 },
    ],
}

export const experiences = [
    {
        role: 'Software Developer Intern',
        company: 'HashedBit Innovations',
        location: 'Gurugram (Remote)',
        duration: 'Dec 2025 – Apr 2026',
        points: [
            'Developed full-stack features using React.js, Node.js, Express.js for real-time client applications',
            'Built and integrated RESTful APIs and managed data using MySQL',
            'Collaborated using Git, GitHub, and Jira in an Agile development environment',
        ],
        tech: ['React.js', 'Node.js', 'Express.js', 'MySQL', 'TypeScript', 'Git', 'Jira'],
        color: '#7c3aed',
    },
    {
        role: 'Web Developer Intern',
        company: 'JSW Steels Ltd.',
        location: 'Dolvi-Pen (Onsite)',
        duration: 'Dec 2024',
        points: [
            'Designed and developed Smart Bus Management System to digitize employee transportation',
            'Built responsive UI with React.js + Bootstrap, RESTful APIs with Node.js + Express.js',
            'Used MongoDB for data storage and enabled real-time bus tracking',
        ],
        tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Bootstrap'],
        color: '#2563eb',
    },
    {
        role: 'Frontend Web Developer Intern',
        company: 'Suvidha Foundation',
        location: 'Remote',
        duration: 'Dec 2024',
        points: [
            'Developed and optimized responsive frontend components to enhance UX and performance',
            'Fixed layout issues and ensured responsive design across devices using Bootstrap',
            'Refactored frontend code for better readability and maintainability',
        ],
        tech: ['React.js', 'Bootstrap'],
        color: '#06b6d4',
    },
]

export const projects = [
    {
        title: 'HealthIQ: AI-Driven Medical Diagnosis System',
        description: 'B.Tech project applying AI to healthcare. Simulates multiple doctor opinions using LLMs, extracts pathology insights via OCR, and features a RAG-powered chatbot.',
        tech: ['Python', 'Streamlit', 'MongoDB', 'OCR', 'OpenAI', 'LangChain', 'RAG'],
        category: 'ML/AI',
        github: 'https://github.com/sarvesh207590/HEALTH-IQ',
        color: '#7c3aed',
        icon: '🧠',
    },
    {
        title: 'BusConnect: Smart Bus Management System',
        description: 'Developed during internship at JSW Steels Ltd. Employees can view bus timetables and routes. Admin interface for route management with real-time notifications.',
        tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Bootstrap'],
        category: 'Web',
        github: 'https://github.com/sarvesh207590/JSW-CONNECT',
        color: '#2563eb',
        icon: '🚌',
    },
    {
        title: 'Epic Cafe — Food Prebooking Website',
        description: 'Eliminated canteen queues with online food prebooking and digital payments. Users browse menu, place orders, get real-time confirmations. Admin panel for menu management.',
        tech: ['Next.js', 'React.js', 'MongoDB', 'CSS'],
        category: 'Web',
        github: 'https://github.com/sarvesh207590/EPIC_CAFE-Next',
        color: '#06b6d4',
        icon: '☕',
    },
    {
        title: 'Bollywood Cinema — Movie Booking App',
        description: 'Multi-page movie booking web app showcasing Indian cinema. Browse movies, view details, book tickets with unique booking ID generation and form validation.',
        tech: ['React', 'Vite', 'Bootstrap', 'JavaScript', 'CSS3'],
        category: 'Web',
        github: 'https://github.com/sarvesh207590/Movie_Booking_Application',
        live: '',
        date: 'Dec 2025',
        color: '#f59e0b',
        icon: '🎬',
    },
    {
        title: 'Heart Disease Predictor',
        description: 'ML-based web app predicting heart disease risk from health parameters. Uses Logistic Regression, Random Forest, KNN with real-time predictions via form input.',
        tech: ['Python', 'Flask', 'Scikit-learn', 'HTML', 'CSS'],
        category: 'ML/AI',
        github: 'https://github.com/sarvesh207590/HEART_DiSEASE_PREDICTOR',
        live: '',
        date: '2024',
        color: '#ef4444',
        icon: '❤️',
    },
    {
        title: 'Food Donation Android App',
        description: 'Connects food donors with NGOs to reduce food waste. Features Firebase Auth, donation tracking, Google Maps integration, donor and NGO modules.',
        tech: ['Java', 'Firebase', 'Google Maps API', 'Android Studio', 'XML'],
        category: 'Android',
        github: 'https://github.com/sarvesh207590/FOOD_DONATION_APP',
        color: '#10b981',
        icon: '🍱',
    },
    {
        title: 'Student Performance Dashboard',
        description: 'Interactive data analytics app for educators. Subject-wise analysis, topper detection, gender comparison with Power BI-inspired UI and custom CSS.',
        tech: ['Python', 'Streamlit', 'Plotly', 'Matplotlib', 'Pandas'],
        category: 'Data',
        github: 'https://github.com/sarvesh207590/Student_Performance_Dashboard',
        color: '#8b5cf6',
        icon: '📊',
    },
]

export const education = [
    {
        degree: 'B.Tech in Information Technology (2022–2026)',
        institution: 'Pillai College of Engineering',
        location: 'Panvel, Navi Mumbai',
        year: 'Nov 2022 – May 2026',
        score: 'CGPA: 9.05',
        icon: '🎓',
    },
    {
        degree: 'Higher Secondary Certificate (HSC)',
        institution: 'Private Highschool & Junior College',
        location: 'Pen, Maharashtra',
        year: '2022',
        score: '75.83%',
        icon: '📚',
    },
    {
        degree: 'Secondary School Certificate (SSC)',
        institution: 'Private Highschool & Junior College',
        location: 'Pen, Maharashtra',
        year: '2020',
        score: '92.40%',
        icon: '🏫',
    },
]

export const certificates = [
    { name: 'HTML, CSS, JavaScript', issuer: 'Great Learning', icon: '🌐' },
    { name: 'Web Development using JavaScript', issuer: 'Pillai College of Engineering (PCE)', icon: '💻' },
    { name: 'PHP and MySQL', issuer: 'Spoken Tutorial (IIT Bombay)', icon: '🗄️' },
    { name: 'Git and GitHub', issuer: 'Infosys Springboard', icon: '🔧' },
]
